export const env = {
  NEXT_PUBLIC_RAZORPAY_KEY_ID: process.env.RAZORPAY_KEY_ID,
  NEXT_PUBLIC_FACEBOOK_PIXEL_ID: process.env.FACEBOOK_PIXEL_ID,
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: process.env.GOOGLE_ANALYTICS_ID,
  NEXT_PUBLIC_CLARITY_ID: process.env.CLARITY_ID,
  NEXT_AI_AGENTS_WA_GROUP_LINK: process.env.AI_AGENTS_WA_GROUP_LINK,
};
